apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.24-stretch
        env:
        - name: POSTGRES_PASSWORD
          value : "trust"
        resources: {}
      restartPolicy: Always
status: {}
